import { View, Text, ScrollView } from 'react-native'
import React from 'react'

export default function Screen2() {
  return (
    <View style={{backgroundColor:"#fff"}}>
      <ScrollView>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      <Text>Screen2</Text>
      </ScrollView>
    </View>
  )
}